<?php

namespace Shirukiz\MangaBundle\Repository;

/**
 * LivreVolumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreVolumeRepository extends \Doctrine\ORM\EntityRepository
{
}
