<?php

namespace Shirukiz\MangaBundle\Repository;

/**
 * VolumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolumeRepository extends \Doctrine\ORM\EntityRepository
{
    function getVolumeA(){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.dateAchat','DESC')
                ->setMaxResults(5)
                ->andWhere('a.possession = :id')
                ->setParameter('id', 1);
        
        return $qb->getQuery()->getResult();
    }

}
