<?php

namespace Shirukiz\FigurineBundle\Repository;

/**
 * FigurineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigurineRepository extends \Doctrine\ORM\EntityRepository
{
    function getFigurine(){
        $qb=$this->createQueryBuilder('a');
        $qb->orderBy('a.nom','ASC');

        return $qb->getQuery()->getResult();
    }
}
