<?php

namespace Shirukiz\JeuxVideoBundle\Repository;

/**
 * MangaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JeuxRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJeux(){
        $qb=$this->createQueryBuilder('a');
        $qb->orderBy('a.nom','ASC');

        return $qb->getQuery()->getResult();
    }
    
    function getJeuxA(){
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date','DESC')
                ->setMaxResults(5);
        
        return $qb->getQuery()->getResult();
    }
}
