#-----------------------------------------------------------------------------Defaut-------------------------------------------------------------------------------------------

shirukiz_manga_homepage:
    path:     /private
    defaults: { _controller: ShirukizMangaBundle:Default:index }


recherche:
    path:      /private/Recherche
    defaults: { _controller: ShirukizMangaBundle:Default:recherche }
    
#-----------------------------------------------------------------------------Manga-------------------------------------------------------------------------------------------

shirukiz_manga_collection:
    path:     /private/Manga
    defaults: { _controller: ShirukizMangaBundle:Manga:MangaCollection }

shirukiz_manga_volume:
    path:      /private/Manga/{id}
    defaults: { _controller: ShirukizMangaBundle:Manga:MangaVolume }
         
volume_ajout:
    path:      /private/Manga/Volume/{id}
    defaults: { _controller: ShirukizMangaBundle:Manga:VolumeAjout }
    
volume_rejet:
    path:      /private/Manga/Volume/Enleve/{id}
    defaults: { _controller: ShirukizMangaBundle:Manga:VolumeRejet }
    
volumeSupp:    
    path:      /private/Manga/Volume/Supp/{id}
    defaults: { _controller: ShirukizMangaBundle:Manga:VolumeSupp }
    
manga_volume_ajout:
    path:      /private/Manga/Ajout/Volume/{id}
    defaults: { _controller: ShirukizMangaBundle:Menu:VolumeAjout }
    
#-----------------------------------------------------------------------------LightNovel-------------------------------------------------------------------------------------------

shirukiz_ln_collection:
    path:     /private/LightNovel
    defaults: { _controller: ShirukizMangaBundle:LightNovel:LightNovelCollection }
    
#-----------------------------------------------------------------------------Jeux-------------------------------------------------------------------------------------------

shirukiz_jeux_collection:
    path:     /private/JeuxVideo
    defaults: { _controller: ShirukizMangaBundle:JeuxVideo:index }
   
jeuxSupp:
    path:     /private/JeuxVideo/Supp/{id}
    defaults: { _controller: ShirukizMangaBundle:JeuxVideo:delete }
    
#---------------------------------------------------------------------------Figurine------------------------------------------------------------------------------------------   
    
shirukiz_figurine_collection:
    path:     /private/Figurine
    defaults: { _controller: ShirukizMangaBundle:Figurine:index }
    
shirukiz_figurine_ajout:
    path:     /private/Figurine/Ajout
    defaults: { _controller: ShirukizMangaBundle:Figurine:ajout }
    
#---------------------------------------------------------------------------Anime------------------------------------------------------------------------------------------   

shirukiz_anime_collection:
    path:     /private/Anime
    defaults: { _controller: ShirukizMangaBundle:Anime:index }